services:
  app:
    image: golang:1.26-alpine3.23
    container_name: authentication_container
    command: sh -c "go run ./cmd/api/main.go"
    depends_on:
      - postgres
      - migrate
    working_dir: /app
    ports:
      - "50051:50051"
    volumes:
      - .:/app
    networks:
      - app-network

  postgres:
    image: postgres:16-alpine
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 4321
      POSTGRES_DB: auth
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  migrate:
    image: migrate/migrate:latest
    container_name: migrate_container
    restart: on-failure
    volumes:
      - ./internal/migrations:/migrations
    command:
      - -path=/migrations
      - -database=postgres://admin:4321@postgres:5432/auth?sslmode=disable
      - up

    depends_on:
      - postgres
    networks:
      - app-network

volumes:
  pgdata:
  migrations:

networks:
  app-network:
    driver: bridge
