services:
  app:
    image: golang:1.26-alpine3.23
    container_name: authentication_container
    working_dir: /app
    command: sh -c "go build -o main . && ./main"
    volumes:
      - .:/app
    networks:
      - app-network

  postgres:
    image: postgres:16-alpine
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 4321
      POSTGRES_DB: auth
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  pgdata:
  pgadmin_data:

networks:
  app-network:
    driver: bridge
