// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/token/token.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckTokenRequest) Reset() {
	*x = CheckTokenRequest{}
	mi := &file_proto_token_token_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckTokenRequest) ProtoMessage() {}

func (x *CheckTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_token_token_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckTokenRequest.ProtoReflect.Descriptor instead.
func (*CheckTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_token_token_proto_rawDescGZIP(), []int{0}
}

func (x *CheckTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type CheckTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckTokenResponse) Reset() {
	*x = CheckTokenResponse{}
	mi := &file_proto_token_token_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckTokenResponse) ProtoMessage() {}

func (x *CheckTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_token_token_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckTokenResponse.ProtoReflect.Descriptor instead.
func (*CheckTokenResponse) Descriptor() ([]byte, []int) {
	return file_proto_token_token_proto_rawDescGZIP(), []int{1}
}

func (x *CheckTokenResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

var File_proto_token_token_proto protoreflect.FileDescriptor

const file_proto_token_token_proto_rawDesc = "" +
	"\n" +
	"\x17proto/token/token.proto\x12\x05token\")\n" +
	"\x11CheckTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"*\n" +
	"\x12CheckTokenResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid2S\n" +
	"\fTokenService\x12C\n" +
	"\fIsTokenValid\x12\x18.token.CheckTokenRequest\x1a\x19.token.CheckTokenResponseB\x18Z\x16./internal/token/protob\x06proto3"

var (
	file_proto_token_token_proto_rawDescOnce sync.Once
	file_proto_token_token_proto_rawDescData []byte
)

func file_proto_token_token_proto_rawDescGZIP() []byte {
	file_proto_token_token_proto_rawDescOnce.Do(func() {
		file_proto_token_token_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_token_token_proto_rawDesc), len(file_proto_token_token_proto_rawDesc)))
	})
	return file_proto_token_token_proto_rawDescData
}

var file_proto_token_token_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_token_token_proto_goTypes = []any{
	(*CheckTokenRequest)(nil),  // 0: token.CheckTokenRequest
	(*CheckTokenResponse)(nil), // 1: token.CheckTokenResponse
}
var file_proto_token_token_proto_depIdxs = []int32{
	0, // 0: token.TokenService.IsTokenValid:input_type -> token.CheckTokenRequest
	1, // 1: token.TokenService.IsTokenValid:output_type -> token.CheckTokenResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_token_token_proto_init() }
func file_proto_token_token_proto_init() {
	if File_proto_token_token_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_token_token_proto_rawDesc), len(file_proto_token_token_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_token_token_proto_goTypes,
		DependencyIndexes: file_proto_token_token_proto_depIdxs,
		MessageInfos:      file_proto_token_token_proto_msgTypes,
	}.Build()
	File_proto_token_token_proto = out.File
	file_proto_token_token_proto_goTypes = nil
	file_proto_token_token_proto_depIdxs = nil
}
